[[datasets]] 
name = 'CLEFIP-0.54M'
link = 'https://github.com/ekamater/CLEFIP-0.54M'
object = 'encoder.pickle'
[[datasets.sections]]
sections_fields = ['Title', 'Abstract', 'Description', 'Claims', 'Applicants', 'Inventors']
[[datasets]] 
name = 'USPTO-2Îœ'
link = 'https://github.com/JasonHoou/USPTO-2M'
object = 'encoder.pickle'
[[datasets.sections]]
sections_fields = ['Title', 'Abstract', 'Concatenated Title and Abstract']
[[datasets]]
name='WIPO'
object = 'encoder.pickle'
sections = 'Title, Abstract, Description, Claims'

[[language_models]]
name = 'wiki-news-300d-1M.vec'
file = 'wiki-news-300d-1M.vec.zip'
object = 'tokenizer.pickle'
description = '1 million word vectors trained on Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset (16B tokens).'
group_name = 'FastText (300-D)'
link = 'https://fasttext.cc'
[[language_models]]
name = 'wiki-news-300d-1M-subword.vec'
file = 'wiki-news-300d-1M-subword.vec.zip'
object = 'tokenizer.pickle'
description = '1 million word vectors trained with subword infomation on Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset (16B tokens).'
group_name = 'FastText (300-D)'
link = 'https://fasttext.cc'
[[language_models]]
name = 'tokenizer_clefip_abstract_60_blstm_Risch'
file = 'tokenizer_clefip_abstract_60_blstm_Risch.zip'
object = 'tokenizer_clefip_abstract_60_blstm_Risch.pickle'
description = 'Rish Tokenizer.'
group_name = 'Rish'
link = 'https://rish.cc'
[[language_models]]
name='crawl-300d-2M.vec'
file = 'crawl-300d-2M.vec.zip'
object = 'tokenizer.pickle'
description = '2 million word vectors trained on Common Crawl (600B tokens).'
group_name = 'FastText (300-D)'
link = 'https://fasttext.cc'
[[language_models]]
name='crawl-300d-2M-subword'
file = 'crawl-300d-2M-subword.zip'
object = 'tokenizer.pickle'
description = ' 2 million word vectors trained with subword information on Common Crawl (600B tokens).'
group_name = 'FastText (300-D)'
link = 'https://fasttext.cc'

[[methods]]
name = 'LSTM'
file = 'lstm_classifier.h5'
object = 'example_classifier.h5'
[[methods]]
name = 'GRU'
file = 'gru_classifier.h5'
object = 'example_classifier.h5'
[[methods]]
name = 'BiLSTM'
file = 'bi-lstm_classifier.h5'
object = 'example_classifier.h5'
[[methods]]
name = 'Bi-GRU'
file = 'bi-gru_classifier.h5'
object = 'example_classifier.h5'
[[methods]]
name = 'Risch_Deep'
file = 'clefip_abstract_60_blstm_Risch.h5'
object = 'clefip_abstract_60_blstm_Risch.h5'

[[ipclevels]]
name = 'Level 1 - Sections'
default = 'no'
[['IPC level']]
name = 'Level 2 - Classes'
default = 'no'
[[ipclevels]]
name = 'Level 3 - Subclasses'
default = 'yes'
[[ipclevels]]
name = 'Level 4 - Groups'
default = 'no'
[[ipclevels]]
name = 'Level 5 - Subgroups '
default = 'no'

[[singlemulti]]
name='single label - main classification code'
[[singlemulti]]
name='multi label - all IPCR codes'

[[structure]]
structure='flat'
[['Structure considered']]
structure='hierarcy'

[['Ensemble']]
name='individual'
default = 'yes'
[['Ensemble modeling']]
name='ensemble'
default = 'no'

[['noofwords']]
value = 60
[['no_of_words']]
value = 100
