#1 Machine Learning Methods
[[methods]]
name = 'LSTM'
file = 'lstm_classifier.h5'
object = 'classifier.h5'
[[methods]]
name = 'GRU'
file = 'gru_classifier.h5'
object = 'classifier.h5'
[[methods]]
name = 'BiLSTM'
file = 'bi-lstm_classifier.h5'
object = 'classifier.h5'
[[methods]]
name = 'Bi-GRU'
file = 'bi-gru_classifier.h5'
object = 'classifier.h5'


#2 Language Models
[[languagemodels]]
name = 'FastText (300-D)'
object = 'tokenizer.pickle'
description = '1 million word vectors trained on Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset (16B tokens).'
link = 'https://fasttext.cc'
[[languagemodels]]
name = 'Risch and Krestel (300-D)'
object = 'tokenizer.pickle'
description = '1 million word vectors trained with subword infomation on Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset (16B tokens).'
link = 'future'

#3  & #4  Datasets & patent Section
[[datasets]]
full_name = 'CLEFIP-0.54M'
name = 'CLEFIP'
link = 'https://github.com/ekamater/CLEFIP-0.54M'
object = 'encoder.pickle'
[[datasets.sections]]
sections_fields = ['Title', 'Abstract', 'Description', 'Claims', 'Applicants', 'Inventors']
[[datasets]] 
full_name = 'USPTO-2Îœ'
name = 'USPTO'
link = 'https://github.com/JasonHoou/USPTO-2M'
object = 'encoder.pickle'
[[datasets.sections]]
sections_fields = ['Title', 'Abstract', 'Concatenated Title and Abstract']
[[datasets]]
full_name='WIPO'
name = 'WIPO'
object = 'encoder.pickle'
sections = 'Title, Abstract, Description, Claims'

#5 IPC Levels
[[ipclevels]]
name = 'Level 1 - Sections'
default = 'no'
[[ipclevels]]
name = 'Level 2 - Classes'
default = 'no'
[[ipclevels]]
name = 'Level 3 - Subclasses'
default = 'yes'
[[ipclevels]]
name = 'Level 4 - Groups'
default = 'no'
[[ipclevels]]
name = 'Level 5 - Subgroups '
default = 'no'

#6 No of Words to be used
[['noofwords']]
value = 60
[['noofwords']]
value = 100

#7 Single/Multi label
[[singlemulti]]
name='single label - main classification code'
[[singlemulti]]
name='multi label - all IPCR codes'

#8 Structure considered
[[structure]]
name='flat'
[[structure]]
name='hierarcy'

#9 Ensemble modeling
[[ensemble]]
name='individual'
default = 'yes'
[[ensemble]]
name='ensemble'
default = 'no'


